#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# To edit the 'workspace' base Image, visit its repository on Github
#    https://github.com/Laradock/workspace
#
# To change its version, see the available Tags on the Docker Hub:
#    https://hub.docker.com/r/laradock/workspace/tags/
#
# Note: Base Image name format {image-tag}-{php-version}
#

ARG LARADOCK_PHP_VERSION

FROM centos:7.6.1810

LABEL maintainer="bravoadmin <bravoadmin@163.com>"

ARG LARADOCK_PHP_VERSION

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

# Start as root
USER root




###########################################################################
# Laradock non-root user:
###########################################################################

# Add a non-root user to prevent files being created with root permissions on host machine.
ARG PUID=1000
ENV PUID ${PUID}
ARG PGID=1000
ENV PGID ${PGID}



# always run apt update when start and after add new source list, then clean up at end.
RUN groupadd -g ${PGID} laradock && \
	groupadd -g 8377 docker_env && \
    useradd -u ${PUID} -g laradock -m laradock -G docker_env && \
    usermod -p "*" laradock


###########################################################################
# Set Timezone
###########################################################################

ARG TZ=UTC
ENV TZ ${TZ}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

###########################################################################
# Install PHP
###########################################################################
# show php
RUN yum update -y
RUN yum list php*
RUN yum -y install wget php* --skip-broken

###########################################################################
# Oracle Install
###########################################################################
RUN mkdir -p ~/work/ora && \
        cd ~/work/ora
#
#
ADD http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/oracle-instantclient18.3-basic-18.3.0.0.0-3.x86_64.rpm ~/work/ora
ADD http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/oracle-instantclient18.3-devel-18.3.0.0.0-3.x86_64.rpm ~/work/ora
ADD http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/getPackage/oracle-instantclient18.3-sqlplus-18.3.0.0.0-3.x86_64.rpm ~/work/ora
#
RUN yum -y install binutils.x86_64 compat-libcap1.x86_64 gcc.x86_64 gcc-c++.x86_64 glibc.i686 glibc.x86_64 glibc-devel.i686 glibc-devel.x86_64 ksh compat-libst+-33 libaio.i686 libaio.x86_64 libaio-devel.i686 libaio-devel.x86_64 libgcc.i686 libgcc.x86_64 libstdc++.i686 libstdc++.x86_64 libstdc++-devel.i686 libstdc++-devx86_64 libXi.i686 libXi.x86_64 libXtst.i686 libXtst.x86_64 make.x86_64 sysstat.x86_64
RUN yum -y localinstall *
#
RUN export LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib:$LD_LIBRARY_PATH && \
         export ORACLE_HOME=/usr/lib/oracle/18.3/client64 && \
         export PATH=/usr/lib/oracle/18.3/client64/bin:$PATH && \
         export C_INCLUDE_PATH=/usr/include/oracle/18.3/client64 && \
		 echo "/usr/lib/oracle/18.3/client64" | pecl install oci8-1.4.10 && \
		 echo "extension=oci8.so" > /etc/php.d/oci8.ini
#
#
#
#--------------------------------------------------------------------------
# Final Touch
#--------------------------------------------------------------------------
#
#
USER root
#
# Clean up
# Set default work directory
WORKDIR /var/www
#
RUN ln -snf /usr/bin/php /usr/local/bin/php