#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM phusion/baseimage:0.9.9

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

RUN DEBIAN_FRONTEND=noninteractive
RUN locale-gen en_US.UTF-8

ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV TERM xterm

# Add the "PHP 5" ppa
#RUN apt-get install -y software-properties-common && \
#    add-apt-repository -y ppa:ondrej/php5
#RUN apt-get update && apt-get install -y python-software-properties software-properties-common && \
#    add-apt-repository ppa:ondrej/php5-oldstable
#apt-get update
#apt-cache policy php5


RUN apt-get update && apt-get install -y python-software-properties software-properties-common

RUN apt-get update && \
    apt-get install -y \
		pkg-config \
        libcurl4-openssl-dev \
        libedit-dev \
		libssl-dev \
		libxml2-dev \
		xz-utils \
		libsqlite3-dev \
		sqlite3 \
		git \
		curl \
		vim \
		nano \
	&& apt-get clean




RUN curl -L -O https://github.com/phpbrew/phpbrew/raw/master/phpbrew
RUN chmod +x phpbrew
RUN mv phpbrew /usr/local/bin/phpbrew


RUN apt-get install -y libbz2-dev bzip2
RUN apt-get install -y libmcrypt-dev gcc make autoconf libc-dev libreadline6 libreadline6-dev
RUN apt-get install -y libxslt-dev

RUN apt-get -y install php5-cli
RUN phpbrew init
RUN phpbrew known --update
RUN phpbrew update
RUN phpbrew install 5.4.34 +default
RUN php -v


#####################################
# Composer:
#####################################

# Install composer and add its bin to the PATH.
RUN curl -s http://getcomposer.org/installer | php && \
    echo "export PATH=${PATH}:/var/www/vendor/bin" >> ~/.bashrc && \
    mv composer.phar /usr/local/bin/composer

# Source the bash
RUN . ~/.bashrc
